/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZanzibarPackagesRouteImport } from './routes/zanzibar-packages'
import { Route as ZanzibarHoneymoonRouteImport } from './routes/zanzibar-honeymoon'
import { Route as TrekkingPackagesRouteImport } from './routes/trekking-packages'
import { Route as TrekkingItineraryRouteImport } from './routes/trekking-itinerary'
import { Route as SafariPackagesRouteImport } from './routes/safari-packages'
import { Route as SafariItinerariesRouteImport } from './routes/safari-itineraries'
import { Route as PlanMyTripRouteImport } from './routes/plan-my-trip'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AccommodationRouteImport } from './routes/accommodation'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToursIndexRouteImport } from './routes/tours.index'
import { Route as ToursSlugRouteImport } from './routes/tours.$slug'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const ZanzibarPackagesRoute = ZanzibarPackagesRouteImport.update({
  id: '/zanzibar-packages',
  path: '/zanzibar-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ZanzibarHoneymoonRoute = ZanzibarHoneymoonRouteImport.update({
  id: '/zanzibar-honeymoon',
  path: '/zanzibar-honeymoon',
  getParentRoute: () => rootRouteImport,
} as any)
const TrekkingPackagesRoute = TrekkingPackagesRouteImport.update({
  id: '/trekking-packages',
  path: '/trekking-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const TrekkingItineraryRoute = TrekkingItineraryRouteImport.update({
  id: '/trekking-itinerary',
  path: '/trekking-itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const SafariPackagesRoute = SafariPackagesRouteImport.update({
  id: '/safari-packages',
  path: '/safari-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const SafariItinerariesRoute = SafariItinerariesRouteImport.update({
  id: '/safari-itineraries',
  path: '/safari-itineraries',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanMyTripRoute = PlanMyTripRouteImport.update({
  id: '/plan-my-trip',
  path: '/plan-my-trip',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationRoute = AccommodationRouteImport.update({
  id: '/accommodation',
  path: '/accommodation',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursIndexRoute = ToursIndexRouteImport.update({
  id: '/tours/',
  path: '/tours/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursSlugRoute = ToursSlugRouteImport.update({
  id: '/tours/$slug',
  path: '/tours/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DestinationsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accommodation': typeof AccommodationRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/experiences': typeof ExperiencesRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/plan-my-trip': typeof PlanMyTripRoute
  '/safari-itineraries': typeof SafariItinerariesRoute
  '/safari-packages': typeof SafariPackagesRoute
  '/trekking-itinerary': typeof TrekkingItineraryRoute
  '/trekking-packages': typeof TrekkingPackagesRoute
  '/zanzibar-honeymoon': typeof ZanzibarHoneymoonRoute
  '/zanzibar-packages': typeof ZanzibarPackagesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/tours/': typeof ToursIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accommodation': typeof AccommodationRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/experiences': typeof ExperiencesRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/plan-my-trip': typeof PlanMyTripRoute
  '/safari-itineraries': typeof SafariItinerariesRoute
  '/safari-packages': typeof SafariPackagesRoute
  '/trekking-itinerary': typeof TrekkingItineraryRoute
  '/trekking-packages': typeof TrekkingPackagesRoute
  '/zanzibar-honeymoon': typeof ZanzibarHoneymoonRoute
  '/zanzibar-packages': typeof ZanzibarPackagesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/tours': typeof ToursIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accommodation': typeof AccommodationRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/experiences': typeof ExperiencesRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/plan-my-trip': typeof PlanMyTripRoute
  '/safari-itineraries': typeof SafariItinerariesRoute
  '/safari-packages': typeof SafariPackagesRoute
  '/trekking-itinerary': typeof TrekkingItineraryRoute
  '/trekking-packages': typeof TrekkingPackagesRoute
  '/zanzibar-honeymoon': typeof ZanzibarHoneymoonRoute
  '/zanzibar-packages': typeof ZanzibarPackagesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/tours/': typeof ToursIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accommodation'
    | '/blog'
    | '/contact'
    | '/destinations'
    | '/experiences'
    | '/faqs'
    | '/gallery'
    | '/plan-my-trip'
    | '/safari-itineraries'
    | '/safari-packages'
    | '/trekking-itinerary'
    | '/trekking-packages'
    | '/zanzibar-honeymoon'
    | '/zanzibar-packages'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/tours/$slug'
    | '/tours/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accommodation'
    | '/blog'
    | '/contact'
    | '/destinations'
    | '/experiences'
    | '/faqs'
    | '/gallery'
    | '/plan-my-trip'
    | '/safari-itineraries'
    | '/safari-packages'
    | '/trekking-itinerary'
    | '/trekking-packages'
    | '/zanzibar-honeymoon'
    | '/zanzibar-packages'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/tours/$slug'
    | '/tours'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accommodation'
    | '/blog'
    | '/contact'
    | '/destinations'
    | '/experiences'
    | '/faqs'
    | '/gallery'
    | '/plan-my-trip'
    | '/safari-itineraries'
    | '/safari-packages'
    | '/trekking-itinerary'
    | '/trekking-packages'
    | '/zanzibar-honeymoon'
    | '/zanzibar-packages'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/tours/$slug'
    | '/tours/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccommodationRoute: typeof AccommodationRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  DestinationsRoute: typeof DestinationsRouteWithChildren
  ExperiencesRoute: typeof ExperiencesRoute
  FaqsRoute: typeof FaqsRoute
  GalleryRoute: typeof GalleryRoute
  PlanMyTripRoute: typeof PlanMyTripRoute
  SafariItinerariesRoute: typeof SafariItinerariesRoute
  SafariPackagesRoute: typeof SafariPackagesRoute
  TrekkingItineraryRoute: typeof TrekkingItineraryRoute
  TrekkingPackagesRoute: typeof TrekkingPackagesRoute
  ZanzibarHoneymoonRoute: typeof ZanzibarHoneymoonRoute
  ZanzibarPackagesRoute: typeof ZanzibarPackagesRoute
  ToursSlugRoute: typeof ToursSlugRoute
  ToursIndexRoute: typeof ToursIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zanzibar-packages': {
      id: '/zanzibar-packages'
      path: '/zanzibar-packages'
      fullPath: '/zanzibar-packages'
      preLoaderRoute: typeof ZanzibarPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zanzibar-honeymoon': {
      id: '/zanzibar-honeymoon'
      path: '/zanzibar-honeymoon'
      fullPath: '/zanzibar-honeymoon'
      preLoaderRoute: typeof ZanzibarHoneymoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trekking-packages': {
      id: '/trekking-packages'
      path: '/trekking-packages'
      fullPath: '/trekking-packages'
      preLoaderRoute: typeof TrekkingPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trekking-itinerary': {
      id: '/trekking-itinerary'
      path: '/trekking-itinerary'
      fullPath: '/trekking-itinerary'
      preLoaderRoute: typeof TrekkingItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safari-packages': {
      id: '/safari-packages'
      path: '/safari-packages'
      fullPath: '/safari-packages'
      preLoaderRoute: typeof SafariPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safari-itineraries': {
      id: '/safari-itineraries'
      path: '/safari-itineraries'
      fullPath: '/safari-itineraries'
      preLoaderRoute: typeof SafariItinerariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-my-trip': {
      id: '/plan-my-trip'
      path: '/plan-my-trip'
      fullPath: '/plan-my-trip'
      preLoaderRoute: typeof PlanMyTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodation': {
      id: '/accommodation'
      path: '/accommodation'
      fullPath: '/accommodation'
      preLoaderRoute: typeof AccommodationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/': {
      id: '/tours/'
      path: '/tours'
      fullPath: '/tours/'
      preLoaderRoute: typeof ToursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$slug': {
      id: '/tours/$slug'
      path: '/tours/$slug'
      fullPath: '/tours/$slug'
      preLoaderRoute: typeof ToursSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DestinationsRouteChildren {
  DestinationsSlugRoute: typeof DestinationsSlugRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsSlugRoute: DestinationsSlugRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccommodationRoute: AccommodationRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  DestinationsRoute: DestinationsRouteWithChildren,
  ExperiencesRoute: ExperiencesRoute,
  FaqsRoute: FaqsRoute,
  GalleryRoute: GalleryRoute,
  PlanMyTripRoute: PlanMyTripRoute,
  SafariItinerariesRoute: SafariItinerariesRoute,
  SafariPackagesRoute: SafariPackagesRoute,
  TrekkingItineraryRoute: TrekkingItineraryRoute,
  TrekkingPackagesRoute: TrekkingPackagesRoute,
  ZanzibarHoneymoonRoute: ZanzibarHoneymoonRoute,
  ZanzibarPackagesRoute: ZanzibarPackagesRoute,
  ToursSlugRoute: ToursSlugRoute,
  ToursIndexRoute: ToursIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
