/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrekkingItineraryRouteImport } from './routes/trekking-itinerary'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as PlanMyTripRouteImport } from './routes/plan-my-trip'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AccommodationRouteImport } from './routes/accommodation'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToursSlugRouteImport } from './routes/tours.$slug'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TrekkingItineraryRoute = TrekkingItineraryRouteImport.update({
  id: '/trekking-itinerary',
  path: '/trekking-itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanMyTripRoute = PlanMyTripRouteImport.update({
  id: '/plan-my-trip',
  path: '/plan-my-trip',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationRoute = AccommodationRouteImport.update({
  id: '/accommodation',
  path: '/accommodation',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursSlugRoute = ToursSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ToursRoute,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DestinationsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accommodation': typeof AccommodationRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/plan-my-trip': typeof PlanMyTripRoute
  '/tours': typeof ToursRouteWithChildren
  '/trekking-itinerary': typeof TrekkingItineraryRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/tours/$slug': typeof ToursSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accommodation': typeof AccommodationRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/plan-my-trip': typeof PlanMyTripRoute
  '/tours': typeof ToursRouteWithChildren
  '/trekking-itinerary': typeof TrekkingItineraryRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/tours/$slug': typeof ToursSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accommodation': typeof AccommodationRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/plan-my-trip': typeof PlanMyTripRoute
  '/tours': typeof ToursRouteWithChildren
  '/trekking-itinerary': typeof TrekkingItineraryRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/tours/$slug': typeof ToursSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accommodation'
    | '/blog'
    | '/contact'
    | '/destinations'
    | '/gallery'
    | '/plan-my-trip'
    | '/tours'
    | '/trekking-itinerary'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/tours/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accommodation'
    | '/blog'
    | '/contact'
    | '/destinations'
    | '/gallery'
    | '/plan-my-trip'
    | '/tours'
    | '/trekking-itinerary'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/tours/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accommodation'
    | '/blog'
    | '/contact'
    | '/destinations'
    | '/gallery'
    | '/plan-my-trip'
    | '/tours'
    | '/trekking-itinerary'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/tours/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccommodationRoute: typeof AccommodationRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  DestinationsRoute: typeof DestinationsRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  PlanMyTripRoute: typeof PlanMyTripRoute
  ToursRoute: typeof ToursRouteWithChildren
  TrekkingItineraryRoute: typeof TrekkingItineraryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trekking-itinerary': {
      id: '/trekking-itinerary'
      path: '/trekking-itinerary'
      fullPath: '/trekking-itinerary'
      preLoaderRoute: typeof TrekkingItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-my-trip': {
      id: '/plan-my-trip'
      path: '/plan-my-trip'
      fullPath: '/plan-my-trip'
      preLoaderRoute: typeof PlanMyTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodation': {
      id: '/accommodation'
      path: '/accommodation'
      fullPath: '/accommodation'
      preLoaderRoute: typeof AccommodationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$slug': {
      id: '/tours/$slug'
      path: '/$slug'
      fullPath: '/tours/$slug'
      preLoaderRoute: typeof ToursSlugRouteImport
      parentRoute: typeof ToursRoute
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DestinationsRouteChildren {
  DestinationsSlugRoute: typeof DestinationsSlugRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsSlugRoute: DestinationsSlugRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

interface ToursRouteChildren {
  ToursSlugRoute: typeof ToursSlugRoute
}

const ToursRouteChildren: ToursRouteChildren = {
  ToursSlugRoute: ToursSlugRoute,
}

const ToursRouteWithChildren = ToursRoute._addFileChildren(ToursRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccommodationRoute: AccommodationRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  DestinationsRoute: DestinationsRouteWithChildren,
  GalleryRoute: GalleryRoute,
  PlanMyTripRoute: PlanMyTripRoute,
  ToursRoute: ToursRouteWithChildren,
  TrekkingItineraryRoute: TrekkingItineraryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
